proto_library(
    name = 'basic_proto',
    srcs = 'basic.proto'
)

proto_library(
    name = 'echo_proto',
    srcs = 'echo_proto'
)

proto_library(
    name = 'horoscope_attr_proto',
    srcs = 'horoscope_attr.proto'
)

