
cc_test(
    name = 'mpserver_autotest',
    srcs = 'mpserver_autotest.cpp',
    deps = [
        '//common/base/string:string',
        '//common/encoding:encoding',
        '//common/net/http:http',
        '//thirdparty/gflags:gflags',
    ]
)

